using Traess.Domain.Enums;

namespace Traess.Api.Contracts;

public record TractorUnitResponse(
    Guid Id,
    string LicensePlate,
    string Brand,
    string Model,
    int Year,
    string ChassisNumber,
    int EnginePowerHp,
    FuelType FuelType,
    decimal GrossVehicleWeightKg,
    decimal MaxTowableWeightKg,
    CouplingType CouplingType,
    bool HasSleepingCabin,
    int SleepingBerths,
    decimal CurrentOdometerKm,
    DateOnly ItvExpiryDate,
    DateOnly InsuranceExpiryDate,
    OwnershipType OwnershipType,
    DateOnly AcquisitionDate,
    FleetVehicleStatus Status,
    string? Notes,
    DateTime CreatedAtUtc,
    DateTime? UpdatedAtUtc);

public record CreateTractorUnitRequest(
    string LicensePlate,
    string Brand,
    string Model,
    int Year,
    string ChassisNumber,
    int EnginePowerHp,
    FuelType FuelType,
    decimal GrossVehicleWeightKg,
    decimal MaxTowableWeightKg,
    CouplingType CouplingType,
    bool HasSleepingCabin,
    int SleepingBerths,
    decimal CurrentOdometerKm,
    DateOnly ItvExpiryDate,
    DateOnly InsuranceExpiryDate,
    OwnershipType OwnershipType,
    DateOnly AcquisitionDate,
    FleetVehicleStatus Status,
    string? Notes);

public record UpdateTractorUnitRequest(
    string LicensePlate,
    string Brand,
    string Model,
    int Year,
    string ChassisNumber,
    int EnginePowerHp,
    FuelType FuelType,
    decimal GrossVehicleWeightKg,
    decimal MaxTowableWeightKg,
    CouplingType CouplingType,
    bool HasSleepingCabin,
    int SleepingBerths,
    decimal CurrentOdometerKm,
    DateOnly ItvExpiryDate,
    DateOnly InsuranceExpiryDate,
    OwnershipType OwnershipType,
    DateOnly AcquisitionDate,
    FleetVehicleStatus Status,
    string? Notes);
